---

- hosts: qaserver
  become: yes
  ignore_errors: yes
    tasks:
      - name: Install packages
        package:
          name: "{{ item }}"
          state: present
        with items:
          - unzip
          - wget
          - httpd
      - name: Download
        shell: 
